services:
  - type: web
    name: mutant-detector-api
    runtime: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx512m
      - key: SPRING_PROFILES_ACTIVE
        value: prod
